---
- name: Export all assets
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Export all assets
    ansible.controller.export:
      all: True
    register: test

  - name: debug
    debug:
      var: test

