---
- name: facts do windows
  hosts: "{{ host_name }}
  tasks:
    - name: start iis service
      win_service:
        name: W3Svc
        state: started

    - name: Gather Ansible Facts About Host
      setup:
        gather_subset:
          - all
    - debug: 
        msg: "{{ ansible_facts }}"
