---
- name: install the iis web service
  hosts: windows
  vars:
    iis_test_message: "Test de Automação"

  tasks:
    - name: install iis
      win_feature:
        name: Web-Server
        state: present

    - name: stop iis service
      win_service:
        name: W3Svc
        state: stopped

