---
- name: Remover host de um inventario de self-healing
  hosts: localhost
  gather_facts: False
  vars:
    host_name: test.acme.com
  tasks:

  - name: Del host
    ansible.controller.host:
      name: "{{ host_name }}"
      inventory: temp_inv-001
      state: present
